# -*- restclient -*-

GET http://127.0.0.1:8085/
#

GET http://127.0.0.1:8085/
Accept: application/json
#

GET http://127.0.0.1:8085/
Accept: text/plain
#

HEAD http://127.0.0.1:8085/
If-None-Match: this-is-a-bogus-etag-hash
#
