---
- name: Place config file in /etc
  become: true
  shell: cp medley.conf.example /etc/medley.conf
  args:
    chdir: "{{ project_root }}"
    creates: /etc/medley.conf

- name: Install medley systemd unit file
  become: true
  copy: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - files/medley.service
  notify: reload systemd

- name: Start medley systemd socket
  become: true
  command: systemctl restart medley.service
