---
- name: Place config file in /etc
  become: true
  shell: cp medley.conf.example /etc/medley.conf
  args:
    chdir: "{{ project_root }}"
    creates: /etc/medley.conf

- name: Install medley systemd unit file
  become: true
  template: src=medley.service dest=/etc/systemd/system/
  notify: reload systemd
