---
- name: Symlink init script
  sudo: yes
  file:
    path="/etc/init.d/{{ project_name }}"
    src="{{ project_root }}/init"
    state="link"
  notify: restart medley

- name: Activate init script
  sudo: yes
  command: update-rc.d {{ project_name }} defaults
  notify: restart medley
