---
- name: Update package index
  become: true
  apt: update_cache=yes cache_valid_time=86400

- name: Create application user
  become: true
  user:
    state=present
    name="{{ project_user }}"
    createhome=yes
    system=yes
    append=yes
    groups="{{ project_user }},audio"

- name: Add ansible ssh user to application user group
  become: true
  user:
    name="{{ ansible_ssh_user }}"
    group="{{ project_user }}"
    append=yes

- name: Create application directories
  become: true
  file:
    path="{{ item }}"
    state=directory
    group={{ project_group }}
    mode=0775
  with_items:
    - /var/{{ project_name }}
    - /var/log/{{ project_name }}
    - /var/cache/{{ project_name }}
    - /var/cache/{{ project_name }}/speak
