---
- name: Update package index
  become: true
  apt: update_cache=yes cache_valid_time=86400

- name: Create application user
  become: true
  user:
    state=present
    name="{{ project_user }}"
    createhome=yes
    system=yes

- name: Add ansible ssh user to application user group
  become: true
  user:
    name="{{ ansible_ssh_user }}"
    group="{{ project_user }}"
    append=yes

- name: Create log directory
  become: true
  file:
    path=/var/log/{{ project_name }}
    state=directory
    group={{ project_group }}
    mode=0775
