---
- name: Install python3 system packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - python3
    - python3-pip
    - python3-lxml

- name: Install virtualenv for python3
  sudo: yes
  pip:
    executable=pip-3.2
    name=virtualenv
    state=present

- name: Create python3 virtualenv
  shell: "virtualenv --system-site-packages --python=python3 {{ project_root }}/venv"
  sudo: yes
  sudo_user: "{{ project_user }}"
  args:
    creates: "{{ project_root }}/bin/python"

- name: Install python3 application packages
  sudo: yes
  sudo_user: "{{ project_user }}"
  pip:
    requirements={{ project_root }}/requirements.txt
    virtualenv={{ project_root }}/venv
