---
- name: Install python3 system packages
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - python3
    - python3-pip
    - python3-lxml
    - python3-dev
    - libasound2-dev

- name: Install virtualenv for python3
  become: true
  pip:
    executable=pip3
    name=virtualenv
    state=present

- name: Create python3 virtualenv
  shell: "virtualenv --system-site-packages --python=python3 {{ project_root }}/venv"
  become: true
  become_user: "{{ project_user }}"
  args:
    creates: "{{ project_root }}/venv/bin/python"

- name: Install python3 application packages
  become: true
  become_user: "{{ project_user }}"
  pip:
    requirements={{ project_root }}/requirements.txt
    virtualenv={{ project_root }}/venv
