---
- name: Install curl
  become: true
  apt: name=curl state=present

- name: Update AWS IP ranges
  become: true
  cron:
    cron_file="{{ project_name }}"
    name="awsranges"
    minute="5"
    hour="7"
    weekday="0"
    job="curl -k --fail --silent --show-error 'https://localhost/awsranges' > /dev/null"
    user="{{ project_user }}"

- name: Update geodb database
  become: true
  cron:
    cron_file="{{ project_name }}"
    name="geodb_update"
    minute="3"
    hour="8"
    day="10"
    job="curl -k --fail --silent --show-error -d 'action=update' 'https://localhost/geodb'"
    user="{{ project_user }}"

- name: Check external ip
  become: true
  cron:
    cron_file="{{ project_name }}"
    name="external_ip"
    minute="45"
    job="curl -X PUT -d 'token=external' -k --fail --silent 'https://localhost/ip' > /dev/null"
    user="{{ project_user }}"
