---
- name: Install curl
  sudo: yes
  apt: name=curl state=present

- name: Update AWS IP ranges
  sudo: yes
  cron:
    cron_file="{{ project_name }}"
    name="awsranges"
    minute="5"
    hour="7"
    weekday="0"
    job="curl -k 'https://localhost/awsranges' > /dev/null"
    user="{{ project_user }}"

- name: Update geodb database
  sudo: yes
  cron:
    cron_file="{{ project_name }}"
    name="geodb_update"
    minute="3"
    hour="8"
    day="10"
    job="curl -s -k -d 'action=update' 'https://localhost/geodb' > /dev/null"
    user="{{ project_user }}"
