---
- name: Install curl
  become: true
  apt: name=curl state=present

- name: Update AWS IP ranges
  become: true
  cron:
    cron_file="{{ project_name }}"
    name="awsranges"
    minute="5"
    hour="7"
    weekday="0"
    job="curl -k --fail --silent --show-error 'https://localhost/awsranges' > /dev/null"
    user="{{ project_user }}"

- name: Update geodb database
  become: true
  cron:
    cron_file="{{ project_name }}"
    name="geodb_update"
    minute="3"
    hour="8"
    day="10"
    job="curl -k --fail --silent --show-error 'https://localhost/geodb/download'"
    user="{{ project_user }}"

- name: Check external ip
  become: true
  cron:
    cron_file="{{ project_name }}"
    name="external_ip"
    minute="45"
    job="curl -X PUT -d 'token=external' -k --fail --silent 'https://localhost/ip' > /dev/null"
    user="{{ project_user }}"

- name: Prune speak cache
  become: true
  cron:
    cron_file="{{ project_name }}"
    name="speak_cache"
    minute="3"
    hour="2"
    job="find /var/cache/medley/speak -type f -daystart -mtime 45 -iname '*.wav' -exec rm {} \;"
    user="{{ project_user }}"
