---
- name: Install python2 packages
  become: true
  apt:
    name={{ item }}
    state=latest
  with_items:
    - python-dev
    - python-pip

- name: Install ansible
  become: true
  pip:
    name=ansible
    state=present
    virtualenv={{ project_root }}
