---
- name: Create application group
  become: true
  group:
    state=present
    name="{{ project_group }}"

- name: Create application user
  become: true
  user:
    state=present
    name="{{ project_user }}"
    createhome=yes
    system=yes
    append=yes
    groups="{{ project_user }},audio"

- name: Put ansible user in application group
  become: true
  user:
    name="{{ ansible_user }}"
    group="{{ project_user }}"
    append=yes

- name: Create application directories
  become: true
  file:
    path="{{ item }}"
    state=directory
    owner="{{ project_user }}"
    group="{{ project_group }}"
    mode=0775
  with_items:
    - /var/log/{{ project_name }}
    - /var/cache/{{ project_name }}
    - /var/cache/{{ project_name }}/speak

- name: Clear template cache (application will recreate)
  become: true
  file:
    path="/var/cache/{{ project_name }}/jinja"
    state="absent"

- name: Install python3 system packages
  become: true
  apt:
    name:
      - python3
      - python3-pip
      - python3-dev
      - python3-venv
      - libasound2-dev
      - make
      - rsync
    state: latest
