---
- name: Create application group
  become: true
  group:
    state=present
    name="{{ project_group }}"

- name: Create application user
  become: true
  user:
    state=present
    name="{{ project_user }}"
    home="{{ project_root }}"
    createhome=no
    system=yes
    append=yes
    groups="{{ project_user }},audio"

- name: Set application user groups
  become: true
  user:
    name="{{ ansible_user }}"
    group="{{ item }}"
    append=yes
  with_items:
    - "{{ project_user }}"
    - "systemd-journal"

- name: Create application directories
  become: true
  file:
    path="{{ item }}"
    state=directory
    owner="{{ project_user }}"
    group="{{ project_group }}"
    mode=0775
  with_items:
    - /var/medley
    - /var/medley/storage

- name: Install system packages
  become: true
  apt:
    name:
      - alsa-utils
      - python3
      - python3-pip
      - python3-venv
      - make
      - nginx-light
      - rsync
    state: latest
