#!/usr/bin/env sh

set -eu

ROOT=$(mktemp -d)

cleanup() {
    rm -rf "$ROOT"
}

echo "Runing pre-commit hook..."

git checkout-index --prefix="$ROOT/" -af

# Excludes deleted, copied, and renamed files.
for CHANGED_FILE in $(git diff --cached --name-only --diff-filter=dcr); do
    ALT_CHANGED_FILE="$ROOT/$CHANGED_FILE"
    FILE_EXTENSION="${ALT_CHANGED_FILE##*.}"
    FILE_NAME=$(basename "${ALT_CHANGED_FILE%.*}")
    PARENT_PATH=$(dirname "$ALT_CHANGED_FILE")
    PARENT_DIR=$(basename "$PARENT_PATH")
    GRANDPARENT_PATH=$(dirname "$PARENT_PATH")
    GRANDPARENT_DIR=$(basename "$GRANDPARENT_PATH")

    if [[ "$FILE_EXTENSION"  != "py" ]]; then
        continue
    fi

    ./venv/bin/flake8 "$ALT_CHANGED_FILE"
    ./venv/bin/pylint --rcfile=.pylintrc "$ALT_CHANGED_FILE"

    if [ "$GRANDPARENT_DIR" = "apps" ]; then
        make "$PARENT_DIR"
    fi

    if [ "$PARENT_DIR" == "parsers" ] || [ "$PARENT_DIR" == "plugins" ]; then
        make "${PARENT_DIR}/${FILE_NAME}.${FILE_EXTENSION}"
    fi
done

trap "cleanup" EXIT
