#!/usr/bin/env sh

set -eu

ROOT=$(mktemp -d)

cleanup() {
    rm -rf $ROOT
}

echo "Runing pre-commit hook..."

mkdir -p $ROOT
git checkout-index --prefix=$ROOT/ -af

# Exclude deleted, copied, and renamed files.
for CHANGED_FILE in $(git diff --cached --name-only --diff-filter=dcr); do
    FILE_EXTENSION="${CHANGED_FILE##*.}"
    FILE_NAME=$(basename "${CHANGED_FILE%.*}")
    PARENT_PATH=$(dirname "$CHANGED_FILE")
    PARENT_DIR=$(basename "$PARENT_PATH")

    if [[ "$FILE_EXTENSION"  == "py" ]]; then
        TEST_FILE="${PARENT_PATH}/test_${FILE_NAME}.py"


        ./venv/bin/flake8 "$CHANGED_FILE"
        ./venv/bin/pylint --rcfile=.pylintrc "$CHANGED_FILE"

        if [ ! -f "$TEST_FILE" ]; then
            continue
        fi

        if [ "$PARENT_DIR" == "parsers" ] || [ "$PARENT_DIR" == "plugins" ]; then
            make "${PARENT_DIR}/${FILE_NAME}.py"
            continue
        fi

        make "$PARENT_DIR"
    fi
done

trap "cleanup" EXIT
