---
- name: Install git package
  sudo: yes
  apt: name=git state=present

- name: Delete backup
  sudo: yes
  file:
    path={{ project_root }}.bak
    state=absent

- name: Backup the current installation
  sudo: yes
  shell: cp -r {{ project_root }} {{ project_root }}.bak
    creates={{ project_root }}.bak

- name: Create application directory
  sudo: yes
  file:
    path={{ project_root }}
    owner={{ project_user }}
    group={{ project_group }}
    state=directory
    mode=0775

- name: Checkout head version of master branch
  sudo: yes
  sudo_user: "{{ project_user }}"
  git:
    repo={{ project_repo }}
    dest={{ project_root }}
    version=HEAD
  notify: restart medley

- name: Make checkout group writable
  sudo: yes
  file:
    path="{{ project_root }}"
    state=directory
    mode=0775