---
- name: Install git package
  become: true
  apt: name=git state=present

- name: Delete backup
  become: true
  file:
    path={{ project_root }}.bak
    state=absent

- name: Current installation stat
  stat:
    path={{ project_root  }}
  register: install_check

- name: Backup the current installation
  become: true
  when: install_check.stat.isdir is defined and install_check.stat.isdir
  shell: cp -r {{ project_root }} {{ project_root }}.bak
    creates={{ project_root }}.bak

- name: Create application directory
  become: true
  file:
    path={{ project_root }}
    owner={{ project_user }}
    group={{ project_group }}
    state=directory
    mode=0775

- name: Checkout head version of master branch
  become: true
  become_user: "{{ project_user }}"
  git:
    repo={{ project_repo }}
    dest={{ project_root }}
    version=HEAD
  notify: stop medley

- name: Make checkout group writable
  become: true
  file:
    path="{{ project_root }}"
    state=directory
    mode=0775
