PUT http://127.0.0.1:8085/blacklist
Content-Type: application/x-www-form-urlencoded

number=x123
#

DELETE http://127.0.0.1:8085/blacklist/?number=x123
Content-Type: application/x-www-form-urlencoded

#
